---
- name: Testing andrewrothstein.krew
  hosts: all
  vars:
    krew_install_plugins:
      - minio
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Krew version
      ansible.builtin.command: /usr/local/bin/krew version
      changed_when: false
      register: krew_test_output
    - name: Krew version
      ansible.builtin.debug:
        msg: '{{ krew_test_output.stdout }}'
    - name: Kubectl krew list
      ansible.builtin.command: sh -lc 'kubectl krew list'
      changed_when: false
      register: krew_list_output
    - name: Kubectl krew list
      ansible.builtin.debug:
        msg: |+
          {{ krew_list_output.stdout }}
          {{ krew_list_output.stderr }}
