---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/krew version
      register: krew_test_output
    - name: krew version
      debug:
        msg: '{{ krew_test_output.stdout }}'
