---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.git
  ansible.builtin.include_role:
    name: andrewrothstein.git
- name: Installing andrewrothstein.kubectl
  ansible.builtin.include_role:
    name: andrewrothstein.kubectl
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ krew_install_exe }}
  ansible.builtin.stat:
    path: '{{ krew_install_exe }}'
  register: krew_binary
  changed_when: false
- name: Downloading and installing krew
  when: not krew_binary.stat.exists
  block:
    - name: Downloading {{ krew_url }} to {{ krew_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ krew_url }}'
        dest: '{{ krew_tmp_tgz }}'
        checksum: '{{ krew_checksum }}'
        mode: '644'
    - name: Mkdir -p {{ krew_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ krew_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ krew_tmp_tgz }} to {{ krew_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ krew_tmp_tgz }}'
        dest: '{{ krew_install_dir }}'
        creates: '{{ krew_install_exe }}'
    - name: Executing "{{ krew_install_exe }} install krew"
      ansible.builtin.command: '{{ krew_install_exe }} install krew'
      changed_when: false
  always:
    - name: Rm -f {{ krew_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ krew_tmp_tgz }}'
        state: absent
- name: Linking {{ krew_link }} to {{ krew_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ krew_install_exe }}'
    dest: '{{ krew_link }}'
    state: link
- name: Add kubectl plugins to the login shell PATH
  become: true
  become_user: root
  with_items:
    - f: kubectl-plugins.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
- name: Installing krew plugins
  when: krew_install_plugins is defined
  block:
    - name: Kubectl krew update
      ansible.builtin.command: sh -lc "kubectl krew update"
      changed_when: false
    - name: Kubectl krew install plugins
      ansible.builtin.command: sh -lc "kubectl krew install {{ item }}"
      changed_when: false
      with_items: '{{ krew_install_plugins }}'
